### ISSUE TITLE
BiocParallel Errors

### ISSUE THREAD

**Issue by minisciencegirl** [rhondabacher/Trendy#5]
I am using trendy on a fairly large dataset with 1339 bulk-RNASeq samples. I've run the median normalization using EBBSeq and created a time vector (either in days or in hours -- if I use days, there will be 4 time points, but if I use hours, there will ~200 time points). I've ensured that I order the columns for the counts in the same order as the time vector. However, when I run trendy, I end up getting: 
`Error: BiocParallel errors
11 remote errors, element index: 1, 1103, 2205, 3307, 4409, 5511, ...
12106 unevaluated and other errors
first remote error:
Error in jitter(tVectIn, 0.1): 'x' must be numeric`

I am running R version 4.2.1
BiocParallel_1.30.3
Trendy_1.18.0

Thank you so much!

**Comment by rhondabacher** [comment]
Thanks for using our package! Can you send me what you are setting tVectIn to?

**Comment by minisciencegirl** [comment]
So I set up my counts and metadata (coldata) using DESeq2 (for simplicity reasons to run multiple downstream analyses). Then I ordered the coldata using the coldata$dol vector, then check to make sure the counts match the coldata using the unique name (coldata$shortname):

#### check to rearrange count names by so that it matches up coldata:
`counts <- counts[, coldata$shortname]
all(coldata$shortname == colnames(counts))`

Followed by the normalization as recommended and then the time vector as follows:

`time.vector <- coldata$dol`

This is a cohort of infants, so I have their age in days or in hours as a numerical vector.
